Add crashdump command
openstack-snaps/snap-microstack pull request #46
Opened 2022-12-12 11:06 UTC by gnuoy

Add `microstack crashdump` command. This is designed to collect data for a bug report. To begin with this just collects a juju status and the juju hooks.

2022-12-12 17:22 UTC, wolsen requested changes

2022-12-12 17:22 UTC, wolsen commented on sunbeam/commands/crashdump.py
> +    """Status of the node.
This shows up as the help for the command, so it should probably have a bit more guidance here.

2022-12-12 17:22 UTC, wolsen commented on sunbeam/commands/crashdump.py
> +@click.argument("output_directory")
If the user specifies the output_directory, won't they be limited only to be able to provide locations in which the snap has access to write it to? As such, I think that it is likely that users will end up specifying something that won't work and be met with some frustrations.

2022-12-14 13:31 UTC, javacruft commented on sunbeam/commands/juju.py
> +                f.write(log)
Capturing the output and then writing it to file could potentially be very memory intensive for a deployment that has been up for a while.

How about using check_call and passing in 'f' as the stdout arg?

   with open(...) as f:
      subprocess.check_call([...], stdout=f)

this would stream the output directly to the file rather than holding the entire blob of data in RAM.

2022-12-14 14:03 UTC, javacruft commented
LGTM - @wolsen I believe your comments have also been addressed so this looks good to land to me.

2022-12-14 14:17 UTC, wolsen approved these changes
lgtm, thanks for the update

2022-12-14 14:17 UTC, merged